### ISSUE TITLE
How can I store the result of galtab.CICTabulator() and the meaning of Warning 'placeholders with weight>1'?

### ISSUE THREAD

**Issue by Sherlockids** [AlanPearl/galtab#2]
1. Given that Galtab employs the tabulation technique similar to Tabcorr, how can I store the output of galtab.CICTabulator() like in Tabcorr?

`halocat = CachedHaloCatalog(simname='bolplanck')`
`halotab = TabCorr.tabulate(halocat, wp, rp_bins, pi_max=40, verbose=True, num_threads=4)`
`halotab.write('bolplanck_wp.hdf5')`
`halotab = TabCorr.read('bolplanck_wp.hdf5')`

Because after I tabulate and try to save the results, it fails:

`gtab = galtab.GalaxyTabulator(halocat, hod)`
`cictab = galtab.CICTabulator(gtab, proj_search_radius, cylinder_half_length, bin_edges=cic_edges)`
`cictab.save('smdpl_cictab_2_10.hdf5')`

where the file `'smdpl_cictab_2_10.hdf5'` is unreadable (`Unable to open file (file signature not found)`).

2. Also, when I try to pass `cictab` into `emcee`, I found it runs very slow, and keeps on telling me that:
`WARNING: There are 80341 placeholders with weight>1, averaging: 1.2103241682052612`

**Comment by Sherlockids** [comment]
Also when I add `cic_galtab = cictab.predict(AssemBias_model)` into my mcmc process, it runs very slow. (over 20 min a step?)

![image](https://github.com/user-attachments/assets/c56a58e6-7ad2-48a6-839d-69d93964fccb)

Code:
`gtab   = galtab.GalaxyTabulator(halocat, hod)`
`cictab = galtab.CICTabulator(gtab, proj_search_radius, cylinder_half_length, bin_edges=cic_edges)`
`def log_prob(x, means, cov, cictab):`
`      ... ...`
`      cic_galtab = cictab.predict(AssemBias_model)`
`      ... ...`
`      return chi_square`

`with Pool(n_cpu) as pool:`
`      sampler = emcee.EnsembleSampler(nwalkers, ndim, log_prob, args=[means, cov, cictab], pool=pool)`
`      state   = sampler.run_mcmc(p0, 2000, progress=True)`
`      sampler.reset()`
`      sampler.run_mcmc(state, nsteps, progress=True)`

**Comment by AlanPearl** [comment]
Hi @Sherlockids, thanks for getting in touch!

1. The CICTabulator class has methods for both saving _and_ reloading the instance. This uses pickling since I never got around to implementing an hdf5 saving mechanism, and pickling was the quick and dirty way to do this. For example, if you save your cictab using `cictab.save('smdpl_cictab_2_10.pickle')`, you can reload it using `cictab = CICTabulator.load('smdpl_cictab_2_10.pickle')`
2. This warning _could_ be easily suppressed by passing `warn_p_over_1=False` to the `predict()` method. However, it is good to understand why this is happening: essentially, you are passing in an AssemBias model in which \<Nsat\> is greater than N_placeholder for certain halos, which invalidates assumptions going into our tabulated CiC algorithm (around the fiducial HOD, we have \<Nsat\> ~ 0.05 * N_placeholder). The best fix is either (a) using a fiducial HOD with more satellites per halo (fiducial hod is set in this line: `gtab = galtab.GalaxyTabulator(halocat, hod)`) or (b) setting a tighter parameter bound on your prior so that you don't feed in hod models with unphysically large numbers of satellites.
3. The prediction runtime we expect certainly will depend strongly on simulation size and \<Nsat\> values of the fiducial HOD, but 20 minutes seems very off in comparison to what I was seeing (closer to 1-5 seconds). My guess is that there is disk swapping going on, which means the memory taken up by the gtab tables are combined larger than your RAM. This is especially likely given that your code snippet shows you are using multiprocessing, and so you have N processes each loading separate instances of the same gtab object, and they are competing for RAM space. I would start with just loading a single gtab table, since they occupy a lot of memory (and it scales with N_halo * N_placeholder). If you need parallelization, the solution might be distributing over computing nodes with MPI.

**Comment by Sherlockids** [comment]
Thanks a lot，I will try your suggestions！

**Comment by Sherlockids** [comment]
Thanks again for your assistance. I have come to realize that I had set the `nwalkers` parameter too high. Perhaps the communications between the walkers were slowing down the computation time per step. By reducing the number of `nwalkers` to `100`, the time per step amounted to approximately `~70s/step`. However, with a more conservative setting of `nwalkers = 20`, the time per step decreased significantly to around `~20s/step`.
